version: '3.8'

services:
  backend:
    build:
      context: ./api
    container_name: truck-fleet-backend
    restart: unless-stopped
    environment:
      # Coolify will inject SERVICE_FQDN_BACKEND_8000 for domain
      - SERVICE_FQDN_BACKEND_8000
      # You can override the database path if you update your code to use an env var
      # - SQLALCHEMY_DATABASE_URL=sqlite:///data/truckfleet.db
    volumes:
      - truckfleet-db:/app/truckfleet-data
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./front-end
    container_name: truck-fleet-frontend
    restart: unless-stopped
    environment:
      # Coolify will inject SERVICE_FQDN_FRONTEND_3000 for domain
      - SERVICE_FQDN_FRONTEND_3000
      # Add VITE_API_URL or similar if your frontend fetches from backend
      # - VITE_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "bun run build && bunx serve ./dist --port 3000 --host 0.0.0.0"

volumes:
  truckfleet-db:
    driver: local
    # This volume will persist the SQLite database file 