version: '3.8'

services:
  backend:
    build:
      context: ./api
    container_name: truck-fleet-backend
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_BACKEND_8000
      # - SQLALCHEMY_DATABASE_URL=sqlite:///data/truckfleet.db
    volumes:
      - truckfleet-db:/app/truckfleet-data
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "pip install gunicorn && gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

  frontend:
    build:
      context: ./front-end
    container_name: truck-fleet-frontend
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_FRONTEND_3000
      - VITE_API_URL=http://backend:8000
    ports:
      - "3000:80"  # Map host port 3000 to container port 80 (Nginx)
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]  # Update to port 80
      interval: 10s
      timeout: 5s
      retries: 5
    # Remove the command since the build happens in the Dockerfile
    # command: sh -c "bun run build && bunx serve ./dist --port 3000 --host 0.0.0.0"

volumes:
  truckfleet-db:
    driver: local