/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/trucks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Trucks */
        get: operations["read_trucks_trucks__get"];
        put?: never;
        /** Create Truck */
        post: operations["create_truck_trucks__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trucks/{truck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Truck */
        get: operations["read_truck_trucks__truck_id__get"];
        /** Update Truck */
        put: operations["update_truck_trucks__truck_id__put"];
        post?: never;
        /** Delete Truck */
        delete: operations["delete_truck_trucks__truck_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Driver */
        get: operations["read_driver_drivers__get"];
        put?: never;
        /** Create Driver */
        post: operations["create_driver_drivers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{driver_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Driver */
        get: operations["read_driver_drivers__driver_id__get"];
        /** Update Driver */
        put: operations["update_driver_drivers__driver_id__put"];
        post?: never;
        /** Delete Driver */
        delete: operations["delete_driver_drivers__driver_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/disable/{driver_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Disable Driver */
        put: operations["disable_driver_drivers_disable__driver_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Jobs */
        get: operations["read_jobs_jobs__get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Job */
        get: operations["read_job_jobs__job_id__get"];
        /** Update Job */
        put: operations["update_job_jobs__job_id__put"];
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Maintenances */
        get: operations["read_maintenances_maintenance__get"];
        put?: never;
        /** Create Maintenance Endpoint */
        post: operations["create_maintenance_endpoint_maintenance__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/{truck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Truck Maintenance */
        get: operations["read_truck_maintenance_maintenance__truck_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/{maintenance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Maintenance */
        get: operations["read_maintenance_maintenance__maintenance_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/{truck_id}/maintenances/{maintenance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Maintenance Endpoint */
        put: operations["update_maintenance_endpoint_maintenance__truck_id__maintenances__maintenance_id__put"];
        post?: never;
        /** Delete Maintenance Endpoint */
        delete: operations["delete_maintenance_endpoint_maintenance__truck_id__maintenances__maintenance_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressBase */
        AddressBase: {
            /** Street */
            street: string;
            /** City */
            city: string;
            /** State */
            state: string;
            /** Zip Code */
            zip_code: string;
        };
        /** CertificationsBase */
        CertificationsBase: {
            /** Hazmat Endorsement */
            hazmat_endorsement: boolean;
            /** Drug Test Date */
            drug_test_date: string;
        };
        /** CurrentAssignmentBase */
        CurrentAssignmentBase: {
            /** Truck Number */
            truck_number: string;
            /** Route */
            route: string;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "on-route" | "loading" | "maintenance" | "off-duty";
        };
        /** DriverCreate */
        DriverCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email: string;
            /** Is Active */
            is_active: boolean;
            address: components["schemas"]["AddressBase"];
            license: components["schemas"]["LicenseBase"];
            employment: components["schemas"]["EmploymentBase"];
            performance: components["schemas"]["PerformanceBase"];
            current_assignment: components["schemas"]["CurrentAssignmentBase"];
            certifications: components["schemas"]["CertificationsBase"];
            emergency_contact: components["schemas"]["EmergencyContactBase"];
        };
        /** DriverOut */
        DriverOut: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email: string;
            /** Is Active */
            is_active: boolean;
            address: components["schemas"]["AddressBase"];
            license: components["schemas"]["LicenseBase"];
            employment: components["schemas"]["EmploymentBase"];
            performance: components["schemas"]["PerformanceBase"];
            current_assignment: components["schemas"]["CurrentAssignmentBase"];
            certifications: components["schemas"]["CertificationsBase"];
            emergency_contact: components["schemas"]["EmergencyContactBase"];
            /** Id */
            id: number;
        };
        /** DriverUpdate */
        DriverUpdate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Phone Number */
            phone_number: string;
            /** Email */
            email: string;
            /** Is Active */
            is_active: boolean;
            address: components["schemas"]["AddressBase"];
            license: components["schemas"]["LicenseBase"];
            employment: components["schemas"]["EmploymentBase"];
            performance: components["schemas"]["PerformanceBase"];
            current_assignment: components["schemas"]["CurrentAssignmentBase"];
            certifications: components["schemas"]["CertificationsBase"];
            emergency_contact: components["schemas"]["EmergencyContactBase"];
        };
        /** EmergencyContactBase */
        EmergencyContactBase: {
            /** Emergency Contact */
            emergency_contact: string;
            /** Relationship */
            relationship: string;
            /** Phone */
            phone: string;
        };
        /** EmploymentBase */
        EmploymentBase: {
            /** Hire Date */
            hire_date: string;
            /** Years Experience */
            years_experience: number;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "inactive" | "on-leave" | "suspended";
            /** Employee Id */
            employee_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreate */
        JobCreate: {
            /** Job Number */
            job_number: string;
            /**
             * Job Date
             * Format: date
             */
            job_date: string;
            /** Job Type */
            job_type: string;
            /** Job Description */
            job_description: string;
            /** Job Status */
            job_status: string;
        };
        /** JobOut */
        JobOut: {
            /** Job Number */
            job_number: string;
            /**
             * Job Date
             * Format: date
             */
            job_date: string;
            /** Job Type */
            job_type: string;
            /** Job Description */
            job_description: string;
            /** Job Status */
            job_status: string;
            /** Id */
            id: number;
        };
        /** JobUpdate */
        JobUpdate: {
            /** Job Number */
            job_number: string;
            /**
             * Job Date
             * Format: date
             */
            job_date: string;
            /** Job Type */
            job_type: string;
            /** Job Description */
            job_description: string;
            /** Job Status */
            job_status: string;
        };
        /** LicenseBase */
        LicenseBase: {
            /** Number */
            number: string;
            /** License Expiration */
            license_expiration: string;
            /** License Class */
            license_class: string;
            /** Is Valid */
            is_valid: boolean;
        };
        /** MaintenanceCreate */
        MaintenanceCreate: {
            /** Truck Id */
            truck_id: number;
            /** Mileage */
            mileage: number;
            /** Description */
            description: string;
            /** Type */
            type: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Next Scheduled
             * Format: date
             */
            next_scheduled: string;
        };
        /** MaintenanceOut */
        MaintenanceOut: {
            /** Truck Id */
            truck_id: number;
            /** Mileage */
            mileage: number;
            /** Description */
            description: string;
            /** Type */
            type: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Next Scheduled
             * Format: date
             */
            next_scheduled: string;
            /** Id */
            id: number;
        };
        /** MaintenanceUpdate */
        MaintenanceUpdate: {
            /** Truck Id */
            truck_id: number;
            /** Mileage */
            mileage: number;
            /** Description */
            description: string;
            /** Type */
            type: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Next Scheduled
             * Format: date
             */
            next_scheduled: string;
        };
        /** PerformanceBase */
        PerformanceBase: {
            /** Safety Rating */
            safety_rating: number;
            /** On Time Delivery Rate */
            on_time_delivery_rate: number;
            /** Total Miles Driven */
            total_miles_driven: number;
            /** Accidents Free */
            accidents_free: number;
        };
        /** TruckCreate */
        TruckCreate: {
            /** Assign Driver */
            assign_driver: string;
            /** Make */
            make: string;
            /** Model */
            model: string;
            /** Year */
            year: number;
            /** Color */
            color: string;
            /** Mileage */
            mileage: number;
            /** Vin */
            vin: string;
            /** Plate */
            plate: string;
        };
        /** TruckOut */
        TruckOut: {
            /** Assign Driver */
            assign_driver: string;
            /** Make */
            make: string;
            /** Model */
            model: string;
            /** Year */
            year: number;
            /** Color */
            color: string;
            /** Mileage */
            mileage: number;
            /** Vin */
            vin: string;
            /** Plate */
            plate: string;
            /** Id */
            id: number;
        };
        /** TruckUpdate */
        TruckUpdate: {
            /** Assign Driver */
            assign_driver: string;
            /** Make */
            make: string;
            /** Model */
            model: string;
            /** Year */
            year: number;
            /** Color */
            color: string;
            /** Mileage */
            mileage: number;
            /** Vin */
            vin: string;
            /** Plate */
            plate: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_trucks_trucks__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckOut"][];
                };
            };
        };
    };
    create_truck_trucks__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TruckCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_truck_trucks__truck_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                truck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_truck_trucks__truck_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                truck_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TruckUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_truck_trucks__truck_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                truck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_driver_drivers__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOut"][];
                };
            };
        };
    };
    create_driver_drivers__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_driver_drivers__driver_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_driver_drivers__driver_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_driver_drivers__driver_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_driver_drivers_disable__driver_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_jobs_jobs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
        };
    };
    create_job_jobs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_jobs__job_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_maintenances_maintenance__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"][];
                };
            };
        };
    };
    create_maintenance_endpoint_maintenance__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_truck_maintenance_maintenance__truck_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                truck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_maintenance_maintenance__maintenance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                maintenance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_maintenance_endpoint_maintenance__truck_id__maintenances__maintenance_id__put: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path: {
                truck_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_maintenance_endpoint_maintenance__truck_id__maintenances__maintenance_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                truck_id: number;
                maintenance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
